### ISSUE TITLE
InputAlignment:null and Parameters:null

### ISSUE THREAD

**Issue by martacds** [dwslab/melt#225]
### Describe the bug
When evaluating a matcher packaged in a docker container both the input alignment and parameters file are null, with the following print:

Source:file:/tmp/MELT-fileupload898333562591763200/source-2357420292010606182.rdf
Target:file:/tmp/MELT-fileupload898333562591763200/target-6807825593059398604.rdf
InputAlignment:null
Parameter:null 

The parameters folder for the track exists and has the necessary files for all testcases. This does not happen when evaluating the matcher directly.

### To Reproduce
Run matching-eval-client in command line or `Executor.run` in Eclipse for the "memoryalpha-stexpanded" testcase in the KG track with a docker container as the system.

- Version of MELT: `3.3`
- Java version: `11`
- Operating system: `Ubuntu 20.04`

#### Full log output
Log: [log.txt](https://github.com/user-attachments/files/16817133/log.txt)

Pom file: [pom.txt](https://github.com/user-attachments/files/16817074/pom.txt)

**Comment by sven-h** [comment]
Hi,

as a first test, you can check that the folder
`/home/marta/oaei_track_cache/oaei.webdatacommons.org/knowledgegraph/v4/parameters/`
exists and contains some files (with the configuration information inside).
If the files do not exist, please delete at least the folder `/home/marta/oaei_track_cache/oaei.webdatacommons.org/knowledgegraph`
and run the evaluation again.

Best regards
Sven

**Comment by martacds** [comment]
Hi,
The folder exists and contains a memoryalpha-stexpanded.rdf file that contains the following text:
{
  "http://oaei.ontologymatching.org/matchingClasses": true,
  "http://oaei.ontologymatching.org/matchingDataProperties": true,
  "http://oaei.ontologymatching.org/matchingObjectProperties": true,
  "http://oaei.ontologymatching.org/matchingRDFProperties": true,
  "http://oaei.ontologymatching.org/matchingInstances": true
}

**Comment by sven-h** [comment]
Hi,

I added some more log outputs to see if it is not sending or not receiving.
Can you run it again but using the most recent version?
To use the most recent version, you just need to change the dependency in the pom.xml.
Further details are explained in https://github.com/dwslab/melt (Section: Developer/Latest Version).

Best regards

**Comment by sven-h** [comment]
Hi,

the new error looks like not all MELT related dependencies are at the newest version.
In case you change one of the dependencies to the developer version, all other MELT dependencies also need to be changed.
In your specific case the `matching-data` artifact is probably not updated.

For the initial bug about the parameters file, I pushed some code changes and now it should work.
Also, the new evaluation client should work with those changes.

Let me know if it works for you as well.

Best regards
Sven

**Comment by martacds** [comment]
Hi,
In our pom, the matching-data artifact is at version 3.3 which I do believe is the latest one.

Some questions:
1. Regarding the parameters file, I'm unsure on which matching-eval version should be in the pom: master-SNAPSHOT or 3.3?
2. Afterwards, I just create the docker container and run the KG testcase with it, right?

**Comment by sven-h** [comment]
Hi,

all melt related artifacts should be at the same version (e.g. `matching-data` and `matching-eval`).
Version 3.3 is released already some time ago and do not reflect the current state (I still need to make a new release).

The version you need to set (such that the parameters file should work) is:
```
<dependency>
    <groupId>com.github.dwslab.melt</groupId>
    <artifactId>matching-eval</artifactId>
    <version>master-SNAPSHOT</version>
</dependency>
```
together with 
```
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
```
in your pom.xml file. Then you use the developer version (which is the most up to date version and reflects the state of the repository). You can also use the [evaluation client](https://dwslab.github.io/melt/matcher-evaluation/client) to execute your system (it is also build based on the developer version). You do not need to package/create your docker container again (the issue was in the code that sends the testcase to the system and not in the receiving part.

**Comment by martacds** [comment]
Hi,
I have both as the 3.3 version.
The pom is set as you said, and I ran the docker with the newest evaluation client and I still get `Parameter:null` in the log: 
[log_console.txt](https://github.com/user-attachments/files/17112874/log_console.txt)

**Comment by sven-h** [comment]
You need to set the version to `master-SNAPSHOT` to get it working or download the [client](https://dwslab.github.io/melt/matcher-evaluation/client).

**Comment by martacds** [comment]
Apologies, I misunderstood your message and thought that only matching-eval had to be set to `master-SNAPSHOT`, and that matching-data and matching-base had to be at 3.3.

Everything appears to be fine now. Thank you so much!
